apiVersion: apps/v1
kind: Deployment
metadata:
  name: amsterdam-app-test
  namespace: test
  labels:
    app: amsterdam-appn-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amsterdam-app-test
  template:
    metadata:
      labels:
        app: amsterdam-app-test
    spec:
      containers:
        - name: amsterdam-test
          image: iamgreatoni/amsterdam-app:test
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: amsterdam-app-test-svc
  namespace: test
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: amsterdam-app-test
